# You can find more wallpapers in ~/.config/ml4w/wallpapers/
# Run ~/.config/hypr/reload-hyprpaper.sh after changing your wallpaper
wallpaper {
	monitor = eDP-1
	path = /home/shayan/.mydotfiles/com.ml4w.hyprlandstarter/.config/ml4w/wallpapers/wallpaper.jpg
}
