// ============================================================
// www.reddit.com.js — Element Remover for Vivaldi custom.js
// Generated by Overlay Remover Builder. Account: Milobowler
// Match pattern: *://www.reddit.com/r/*/comments/*
// ============================================================
(function () {
  "use strict";

  const LOG = (s) => console.log("[Remover:www.reddit.com]", s);

  const TARGET_DOMAIN = "www.reddit.com";

  // Matches: *://www.reddit.com/r/*/comments/*
  const URL_PATTERN = new RegExp(
    "^https?://www\.reddit\.com/r/.*/comments/.*$",
  );

  // Defined at top level so both injectCSS and injectJS can access it
  const selectors = [
    "#left-sidebar",
    "#flex-left-nav-container",
    "#left-sidebar-container",
    "div.pe-lg.flex.gap-xs.items-center.justify-start",
    "#notifications-inbox-button",
  ];

  // Stored as a single const so insertCSS and removeCSS use identical text
  const CSS_RULES = selectors
    .map((s) => s + " { display: none !important; }")
    .join("\n");

  // --- This function runs INSIDE the page (injected via chrome.scripting) ---
  // Must be fully self-contained — no references to outer scope variables
  function pageScript(selectors, urlPatternStr) {
    const FLAG = "__overlayRemoverActive_www_reddit_com";
    if (window[FLAG]) return;
    window[FLAG] = true;
    console.log("[Remover:www.reddit.com] Active");

    const URL_PATTERN = new RegExp(urlPatternStr);

    function isCurrentUrlMatch() {
      return URL_PATTERN.test(location.href);
    }

    function removeElements() {
      if (!isCurrentUrlMatch()) return 0;
      let count = 0;
      selectors.forEach(function (selector) {
        try {
          document.querySelectorAll(selector).forEach(function (el) {
            el.remove();
            count++;
          });
        } catch (e) {
          /* ignore bad selectors */
        }
      });
      if (count)
        console.log(
          "[Remover:www.reddit.com] Removed " + count + " element(s)",
        );
      return count;
    }

    var debounceTimer = null;
    function debouncedRemove(delay) {
      clearTimeout(debounceTimer);
      debounceTimer = setTimeout(removeElements, delay || 150);
    }

    setTimeout(removeElements, 200);
    setTimeout(removeElements, 1500);

    var lastUrl = location.href;
    new MutationObserver(function () {
      if (location.href !== lastUrl) {
        lastUrl = location.href;
        console.log("[Remover:www.reddit.com] URL changed → " + location.href);
        debouncedRemove(600);
      }
    }).observe(document.documentElement, { childList: true, subtree: true });

    new MutationObserver(function () {
      debouncedRemove(150);
    }).observe(document.documentElement, { childList: true, subtree: true });
  }

  // --- Background-side helpers ---

  function injectCSS(tabId) {
    if (!chrome.scripting) return;
    chrome.scripting
      .insertCSS({
        target: { tabId: tabId },
        css: CSS_RULES,
        origin: "USER",
      })
      .catch(function (e) {
        LOG("CSS inject failed: " + e);
      });
  }

  function removeCSS(tabId) {
    if (!chrome.scripting) return;
    chrome.scripting
      .removeCSS({
        target: { tabId: tabId },
        css: CSS_RULES,
        origin: "USER",
      })
      .catch(function (e) {
        LOG("CSS remove failed: " + e);
      });
  }

  function injectJS(tabId) {
    if (!chrome.scripting) return;
    chrome.scripting
      .executeScript({
        target: { tabId: tabId, allFrames: false },
        world: "MAIN",
        func: pageScript,
        args: [selectors, "^https?://www\.reddit\.com/r/.*/comments/.*$"],
      })
      .then(function () {
        LOG("JS injected into tab " + tabId);
      })
      .catch(function (e) {
        LOG("JS inject failed: " + e);
      });
  }

  function isTargetUrl(url) {
    return url && URL_PATTERN.test(url);
  }

  function isSameDomain(url) {
    return url && url.includes(TARGET_DOMAIN);
  }

  function attachListeners() {
    LOG("Attaching listeners — pattern: *://www.reddit.com/r/*/comments/*");

    // onCommitted fires before the page renders — inject CSS if match, remove if not
    if (chrome.webNavigation && chrome.webNavigation.onCommitted) {
      chrome.webNavigation.onCommitted.addListener(function (details) {
        if (details.frameId !== 0) return;
        if (isTargetUrl(details.url)) {
          injectCSS(details.tabId);
        } else if (isSameDomain(details.url)) {
          removeCSS(details.tabId);
        }
      });
      LOG("Listening via chrome.webNavigation.onCommitted");
    }

    // onUpdated complete — JS cleanup after load
    if (chrome.tabs && chrome.tabs.onUpdated) {
      chrome.tabs.onUpdated.addListener(function (tabId, changeInfo, tab) {
        if (changeInfo.status === "complete" && tab.url) {
          if (isTargetUrl(tab.url)) {
            injectJS(tabId);
          }
        }
        // SPA navigations that don't trigger a full reload
        if (changeInfo.url && isSameDomain(changeInfo.url)) {
          if (isTargetUrl(changeInfo.url)) {
            setTimeout(function () {
              injectCSS(tabId);
              injectJS(tabId);
            }, 700);
          } else {
            setTimeout(function () {
              removeCSS(tabId);
            }, 700);
          }
        }
      });
      LOG("Listening via chrome.tabs.onUpdated");
    }

    // history.pushState / replaceState navigations
    if (chrome.webNavigation && chrome.webNavigation.onHistoryStateUpdated) {
      chrome.webNavigation.onHistoryStateUpdated.addListener(
        function (details) {
          if (details.frameId !== 0) return;
          if (isTargetUrl(details.url)) {
            setTimeout(function () {
              injectCSS(details.tabId);
              injectJS(details.tabId);
            }, 700);
          } else if (isSameDomain(details.url)) {
            setTimeout(function () {
              removeCSS(details.tabId);
            }, 700);
          }
        },
      );
      LOG("Listening via chrome.webNavigation.onHistoryStateUpdated");
    }
  }

  // Poll until chrome.tabs API is ready (Vivaldi loads APIs asynchronously)
  var attempts = 0;
  function waitForApis() {
    if (chrome && chrome.tabs && chrome.tabs.onUpdated) {
      LOG("APIs ready after " + attempts + " attempt(s)");
      attachListeners();
    } else if (attempts++ < 40) {
      setTimeout(waitForApis, 250);
    } else {
      LOG("Gave up waiting for chrome.tabs API");
    }
  }

  waitForApis();
})();
